# Generated by Django 3.2.11 on 2022-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentrollno', models.IntegerField(max_length=20)),
                ('studentname', models.CharField(max_length=39)),
                ('studentclass', models.IntegerField(max_length=15)),
                ('school', models.CharField(max_length=40)),
                ('mobile', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
