# Generated by Django 3.2.11 on 2022-01-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentacademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentrollno', models.IntegerField(max_length=10)),
                ('maths', models.IntegerField(max_length=100)),
                ('physics', models.IntegerField(max_length=100)),
                ('chemistry', models.IntegerField(max_length=100)),
                ('biology', models.IntegerField(max_length=100)),
                ('english', models.IntegerField(max_length=100)),
            ],
        ),
    ]
